name: plant_counting
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - tqdm
  - keras
  - PIL
  - matplotlib
  - scikit-image
  - scikit-learn
  - python==3.7.1
  - tensorflow-gpu
  - seaborn
